"""Shopify store schema fixes

Revision ID: ec874cd49ce3
Revises: f9dea2f5ec5e
Create Date: 2024-04-13 20:10:44.499633

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "ec874cd49ce3"
down_revision: Union[str, None] = "f9dea2f5ec5e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "shopify_stores", "access_token", existing_type=sa.VARCHAR(), nullable=True
    )
    op.drop_column("shopify_stores", "created_at")
    op.drop_column("shopify_stores", "updated_at")
    op.drop_column("shopify_stores", "deleted_at")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "shopify_stores",
        sa.Column("deleted_at", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "shopify_stores",
        sa.Column("updated_at", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "shopify_stores",
        sa.Column("created_at", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "shopify_stores", "access_token", existing_type=sa.VARCHAR(), nullable=False
    )
    # ### end Alembic commands ###
