"""Shopify store schema fixes

Revision ID: f17b8aeeb6a2
Revises: ec874cd49ce3
Create Date: 2024-04-14 16:08:09.664806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f17b8aeeb6a2'
down_revision: Union[str, None] = 'ec874cd49ce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('shopify_stores', 'is_app_installed')
    op.drop_column('shopify_stores', 'state')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('shopify_stores', sa.Column('state', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('shopify_stores', sa.Column('is_app_installed', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
